#import <Foundation/Foundation.h>

/// Forward-declare the Swift entry point generated by the NitroNotification Swift module.
/// This is declared in NitroNotification-Swift.h but we avoid importing that header
/// to stay away from the C++ umbrella chain.
extern "C" void NitroNotification_setup(void);

@interface NitroNotificationLoader : NSObject
@end

@implementation NitroNotificationLoader

+ (void)load {
  // Touch NotificationHub.shared via the Swift @_cdecl shim so the
  // UNUserNotificationCenterDelegate is registered before any foreground
  // notification can arrive — without requiring an import in the app delegate.
  NitroNotification_setup();
}

@end
